export const words = [
  {
    centerLetter: "a",
    outerLetters: ["t", "u", "k", "m", "n", "o"],
    validLetters: ["t", "u", "k", "a", "m", "n", "o"],
    pangrams: ["komutan", "okutman"],
    answers: [
      "aktutma",
      "akut",
      "amut",
      "anut",
      "atakum",
      "koku",
      "kokutma",
      "kokutmak",
      "komut",
      "komuta",
      "komutan",
      "konut",
      "kota",
      "kuantum",
      "kunt",
      "kutan",
      "kutnu",
      "kutu",
      "kuut",
      "maktu",
      "mamut",
      "mukataa",
      "muta",
      "mutantan",
      "mutat",
      "natuk",
      "nukut",
      "nutuk",
      "okuntu",
      "okutma",
      "okutmak",
      "okutman",
      "takatuka",
      "tamu",
      "taun",
      "tuman",
      "tutak",
      "tutam",
      "tutamak",
      "tutanak",
      "tutku",
      "tutkun",
      "tutma",
      "tutmak",
      "tutu",
      "tutuk",
      "tutum",
      "tutunma",
      "tutunmak",
      "umut",
      "unutkan",
      "unutma",
      "unutmak",
      "utanma",
      "utanmak",
      "utku",
      "utma",
      "utmak",
      "atom",
      "makul",
      "kutu",
      "konum",
      "takım",
      "otokar",
      "katı",
    ],
    id: "1",
  },
  {
    centerLetter: "a",
    outerLetters: ["v", "t", "l", "i", "y", "e"],
    validLetters: ["v", "t", "l", "a", "i", "y", "e"],
    pangrams: ["vilayet"],
    answers: [
      "aile",
      "avla",
      "vali",
      "veya",
      "ayet",
      "alay",
      "veli",
      "tava",
      "yayla",
      "ayva",
      "talay",
      "yatay",
      "tavla",
      "yaya",
      "vilayet",
      "villa",
      "vaat",
      
    ],
    id: "2",
  },
  {
    centerLetter: "a",
    outerLetters: ["t", "y", "z", "i", "f", "e"],
    validLetters: ["t", "e", "z", "a", "i", "f", "y"],
    pangrams: ["ziyafet"],
    answers: [
      "ziyafet",
      "zeytin",
      "ziyan",
      "zayi",
      "ayin",
      "azat",
      "afet",
      "aziz",
      "ayaz",
      "ayet",
      "tezat",
      "faiz",
    ],
  },
];
