export const words = [
  {
    centerLetter: "e",
    outerLetters: ["b", "i", "l", "o", "p", "w"],
    validLetters: ["b", "i", "l", "e", "o", "p", "w"],
    pangrams: ["blowpipe"],
    answers: [
      "blowpipe",
      "bebop",
      "beep",
      "belie",
      "bell",
      "belle",
      "bellow",
      "below",
      "bible",
      "bile",
      "bleep",
      "blew",
      "bobble",
      "bowel",
      "elbow",
      "elope",
      "epee",
      "libel",
      "libelee",
      "lobe",
      "lope",
      "oboe",
      "oleo",
      "ollie",
      "pebble",
      "peel",
      "peep",
      "peewee",
      "people",
      "pewee",
      "pile",
      "pipe",
      "pleb",
      "plebe",
      "plie",
      "pole",
      "pope",
      "weep",
      "weepie",
      "well",
      "wile",
      "wipe",
      "wobble",
    ],
  },

  {
    centerLetter: "r",
    outerLetters: ["a", "i", "l", "t", "u", "v"],
    validLetters: ["a", "i", "l", "r", "t", "u", "v"],
    pangrams: ["virtual"],
    answers: [
      "virtual",
      "altar",
      "aria",
      "aril",
      "arrival",
      "atria",
      "atrial",
      "attar",
      "aura",
      "aural",
      "avatar",
      "lair",
      "lariat",
      "larva",
      "larval",
      "liar",
      "lira",
      "rail",
      "raita",
      "ratatat",
      "rattail",
      "rial",
      "rill",
      "ritual",
      "rival",
      "rural",
      "tart",
      "tartar",
      "tiara",
      "titular",
      "trail",
      "trait",
      "travail",
      "trial",
      "trill",
      "trivia",
      "trivial",
      "ultra",
      "uvular",
      "viral",
      "vulvar",
    ],
  },
  {
    centerLetter: "o",
    outerLetters: ["b", "i", "l", "m", "e", "z"],
    validLetters: ["b", "i", "l", "o", "m", "e", "z"],
    pangrams: ["immobilize", "mobilize"],
    answers: [
      "biome",
      "blob",
      "bloom",
      "bobble",
      "boil",
      "boll",
      "bolo",
      "bomb",
      "bombe",
      "boob",
      "booboo",
      "boom",
      "booze",
      "bozo",
      "immobile",
      "immobilize",
      "limbo",
      "limo",
      "lobe",
      "lobo",
      "loll",
      "loom",
      "memo",
      "mezzo",
      "mimeo",
      "mobile",
      "mobilize",
      "moil",
      "mole",
      "moll",
      "oboe",
      "oleo",
      "olio",
      "ollie",
      "ooze",
      "zombie",
      "zoom",
    ],
  },
  {
    centerLetter: "a",
    outerLetters: ["b", "i", "r", "t", "u", "y"],
    validLetters: ["b", "i", "r", "a", "t", "u", "y"],
    pangrams: ["tributary"],
    answers: [
      "abut",
      "arbitrary",
      "arty",
      "atria",
      "attar",
      "bait",
      "barbarity",
      "batty",
      "brat",
      "bratty",
      "brut",
      "burrata",
      "butt",
      "itty",
      "rabbit",
      "raita",
      "rarity",
      "ratatat",
      "ratty",
      "ribbit",
      "rutty",
      "tabby",
      "tarry",
      "tart",
      "tartar",
      "tatty",
      "taut",
      "tiara",
      "tibia",
      "trait",
      "tray",
      "tributary",
      "tuba",
      "tubby",
      "tutti",
      "tutu",
      "yurt",
    ],
  },
  {
    centerLetter: "d",
    outerLetters: ["b", "c", "e", "j", "o", "t"],
    validLetters: ["b", "c", "e", "d", "j", "o", "t"],
    pangrams: ["objected"],
    answers: [
      "beet",
      "boot",
      "booted",
      "bootee",
      "coot",
      "cote",
      "debt",
      "decoc",
      "decoced",
      "deject",
      "dejected",
      "detect",
      "detected",
      "dote",
      "doted",
      "dotted",
      "eject",
      "ejected",
      "jete",
      "jetted",
      "jotted",
      "object",
      "objected",
      "octet",
      "teed",
      "toed",
      "toot",
      "tooted",
      "tote",
      "toted",
    ],
  },
  {
    centerLetter: "a",
    outerLetters: ["g", "i", "l", "n", "t", "v"],
    validLetters: ["g", "i", "l", "a", "n", "t", "v"],
    pangrams: ["gallivant", "gallivanting", "vigilant"],
    answers: [
      "ailing",
      "alga",
      "algal",
      "align",
      "aligning",
      "alit",
      "anal",
      "angling",
      "annal",
      "anvil",
      "atilt",
      "avail",
      "availing",
      "gala",
      "galangal",
      "gall",
      "gallant",
      "galling",
      "gallivant",
      "gallivanting",
      "ganglia",
      "gangling",
      "giggling",
      "gill",
      "gilling",
      "gilt",
      "glia",
      "glint",
      "glinting",
      "initial",
      "initialing",
      "lagging",
      "lain",
      "lanai",
      "lantana",
      "lava",
      "laving",
      "ligating",
      "lilt",
      "lilting",
      "lining",
      "lint",
      "litigant",
      "litigating",
      "living",
      "nail",
      "nailing",
      "natal",
      "naval",
      "niggling",
      "tail",
      "tailgating",
      "tailing",
      "tali",
      "tall",
      "tallit",
      "tangling",
      "tattling",
      "tiling",
      "till",
      "tilling",
      "tilt",
      "tilting",
      "tingling",
      "titillating",
      "vagal",
      "vaginal",
      "valiant",
      "vanilla",
      "vanillin",
      "vial",
      "vigil",
      "vigilant",
      "villa",
      "villain",
      "vital",
    ],
  },
  {
    centerLetter: "p",
    outerLetters: ["a", "f", "i", "l", "n", "t"],
    validLetters: ["a", "f", "i", "p", "l", "n", "t"],
    pangrams: ["flippant", "plaintiff"],
    answers: [
      "apian",
      "appall",
      "fillip",
      "flap",
      "flip",
      "flippant",
      "inapt",
      "pail",
      "pain",
      "paint",
      "palapa",
      "palatal",
      "palatial",
      "pall",
      "palp",
      "panini",
      "pant",
      "papa",
      "papal",
      "papilla",
      "patina",
      "pfft",
      "pilaf",
      "pill",
      "pinata",
      "pint",
      "pintail",
      "pipit",
      "pippin",
      "pita",
      "pitapat",
      "pitfall",
      "plain",
      "plaint",
      "plaintiff",
      "plait",
      "plan",
      "plant",
      "plantain",
      "plat",
      "pliant",
      "tapa",
      "tilapia",
    ],
  },
  {
    centerLetter: "m",
    outerLetters: ["c", "e", "i", "l", "n", "t"],
    validLetters: ["c", "e", "i", "m", "l", "n", "t"],
    pangrams: ["clementine", "inclement"],
    answers: [
      "cement",
      "clement",
      "clementine",
      "clime",
      "element",
      "emcee",
      "emetic",
      "eminence",
      "eminent",
      "emit",
      "enticement",
      "entitlement",
      "icemen",
      "imminence",
      "imminent",
      "incitement",
      "inclement",
      "item",
      "lime",
      "limit",
      "limn",
      "linemen",
      "liniment",
      "meet",
      "melee",
      "melt",
      "meme",
      "mentee",
      "mete",
      "mettle",
      "mice",
      "mien",
      "mile",
      "mill",
      "millet",
      "mime",
      "mimetic",
      "mimic",
      "mince",
      "mine",
      "mini",
      "minim",
      "mint",
      "mite",
      "mitt",
      "mitten",
      "teem",
      "tenement",
      "time",
      "timeline",
      "titmice",
    ],
  },
  {
    centerLetter: "n",
    outerLetters: ["a", "c", "k", "l", "u","o"],
    validLetters: ["a", "c", "k", "n", "l", "u","o"],
    pangrams: ["uncloak"],
    answers: [
      "anal",
      "annal",
      "annual",
      "annul",
      "anon",
      "canal",
      "cancan",
      "canna",
      "cannon",
      "cannula",
      "canola",
      "canon",
      "clan",
      "clank",
      "clonk",
      "clunk",
      "cocoon",
      "colcannon",
      "colon",
      "conk",
      "knack",
      "knock",
      "knoll",
      "koan",
      "lacuna",
      "lank",
      "llano",
      "loan",
      "loon",
      "luna",
      "lunk",
      "lunula",
      "naan",
      "nana",
      "nock",
      "nonlocal",
      "nook",
      "noon",
      "noun",
      "null",
      "ulna",
      "uncloak",
      "uncock",
      "uncool",
      "unlock",
    ],
  },
  {
    centerLetter: "f",
    outerLetters: ["a", "b", "d", "l", "o", "r"],
    validLetters: ["a", "b", "d", "f", "l", "o", "r"],
    pangrams: ["floorboard"],
    answers: [
      "aboard",
      "abroad",
      "adobo",
      "arbor",
      "baba",
      "bald",
      "ball",
      "ballad",
      "baobab",
      "barb",
      "bard",
      "barf",
      "blab",
      "blob",
      "blood",
      "boar",
      "board",
      "boba",
      "boffo",
      "bola",
      "bold",
      "boll",
      "bollard",
      "bolo",
      "boob",
      "booboo",
      "boor",
      "brad",
      "broad",
      "brood",
      "drab",
      "flab",
      "floorboard",
      "labor",
      "lobo",
      "oddball",
      "rollbar",
    ],
  },
];
