
export const words = [
  {
    centerLetter: "e",
    outerLetters: ["b", "i", "l", "o", "p", "w"],
    validLetters: ["b", "i", "l", "e", "o", "p", "w"],
    pangrams: ["blowpipe"],
    answers: [
      "blowpipe",
      "bebop",
      "beep",
      "belie",
      "bell",
      "belle",
      "bellow",
      "below",
      "bible",
      "bile",
      "bleep",
      "blew",
      "bobble",
      "bowel",
      "elbow",
      "elope",
      "epee",
      "libel",
      "libelee",
      "lobe",
      "lope",
      "oboe",
      "oleo",
      "ollie",
      "pebble",
      "peel",
      "peep",
      "peewee",
      "people",
      "pewee",
      "pile",
      "pipe",
      "pleb",
      "plebe",
      "plie",
      "pole",
      "pope",
      "weep",
      "weepie",
      "well",
      "wile",
      "wipe",
      "wobble",
    ],
  },

  {
    centerLetter: "r",
    outerLetters: ["a", "i", "l", "t", "u", "v"],
    validLetters: ["a", "i", "l", "r", "t", "u", "v"],
    pangrams: ["virtual"],
    answers: [
      "virtual",
      "altar",
      "aria",
      "aril",
      "arrival",
      "atria",
      "atrial",
      "attar",
      "aura",
      "aural",
      "avatar",
      "lair",
      "lariat",
      "larva",
      "larval",
      "liar",
      "lira",
      "rail",
      "raita",
      "ratatat",
      "rattail",
      "rial",
      "rill",
      "ritual",
      "rival",
      "rural",
      "tart",
      "tartar",
      "tiara",
      "titular",
      "trail",
      "trait",
      "travail",
      "trial",
      "trill",
      "trivia",
      "trivial",
      "ultra",
      "uvular",
      "viral",
      "vulvar",
    ],
  },
];
