
export const words = [
  {
    centerLetter: "t",
    outerLetters: ["t", "u", "k", "m", "n", "o"],
    validLetters: ["a", "t", "u", "k", "m", "n", "o"],
    pangrams: ["aktutma"],
    answers: [
      "aktutma",
      "akut",
      "amut",
      "anut",
      "atakum",
      "koku",
      "kokutma",
      "kokutmak",
      "komut",
      "komuta",
      "komutan",
      "konut",
      "kuantum",
      "kunt",
      "kutan",
      "kutnu",
      "kutu",
      "kuut",
      "maktu",
      "mamut",
      "mukataa",
      "muta",
      "mutantan",
      "mutat",
      "natuk",
      "nukut",
      "nutuk",
      "okuntu",
      "okutma",
      "okutmak",
      "okutman",
      "takatuka",
      "tamu",
      "taun",
      "tuman",
      "tutak",
      "tutam",
      "tutamak",
      "tutanak",
      "tutku",
      "tutkun",
      "tutma",
      "tutmak",
      "tutu",
      "tutuk",
      "tutum",
      "tutunma",
      "tutunmak",
      "umut",
      "unutkan",
      "unutma",
      "unutmak",
      "utanma",
      "utanmak",
      "utku",
      "utma",
      "utmak",
    ],
    id: "1",
  },
];
